# general
gpu_id: 0
use_gpu: True
DDP: False
seed: 2020
state: INFO
reproducibility: True
data_path: 'dataset/'
checkpoint_dir: 'saved/'
generated_text_dir: 'generated/'

# training settings
epochs: 50
train_batch_size: 64
learner: adam
learning_rate: 0.001
eval_step: 1
stopping_step: 3
grad_clip: 5.0

# evaluation settings
metrics: ["bleu", "self_bleu"]
n_grams: [1,2,3,4,5]
eval_batch_size: 64
eval_generate_num: 10000
