# general
gpu_id: 0
use_gpu: True
seed: 2020
state: INFO
reproducibility: True
data_path: 'dataset/'
checkpoint_dir: 'saved'

# training settings
epochs: 10
train_batch_size: 64
learner: adam
learning_rate: 0.001
training_neg_sample_num: 1
eval_step: 2
stopping_step: 10

# evaluation settings
eval_setting: RO_RS,full
group_by_user: True
split_ratio: [0.8,0.1,0.1]
leave_one_num: 2
real_time_process: True
metrics: ["bleu", "self_bleu"]
n_grams: [1,2,3,4]
topk: [10]
valid_metric: MRR@10
eval_batch_size: 64

# GAN training settings
g_pretraining_epochs: 80
d_pretraining_epochs: 50
d_sample_num: 10000
d_sample_training_epochs: 3
adversarail_training_epochs: 120
adversarail_d_epochs: 5
grad_clip: 5.0

