# model settings
embedding_size: 256
hidden_size: 512
latent_size: 256
prior_neuron_size: 512
posterior_neuron_size: 512
latent_neuron_size: 512
rnn_type: "gru"
num_enc_layers: 2
num_dec_layers: 2
bidirectional: True

# training settings
learning_rate: 0.0001
dropout_ratio: 0.2
