embedding_size: 400
hidden_size: 500
field_size: 50       
pos_size: 5
position_vocab: 31
dual_attention: True
fgate_encoder: True
field: True
position: True
encoder_pos: True
decoder_pos: True
max_length: 150
grad_clip: 0.5
metrics: ['bleu', 'rouge']
stopping_step: 3

train_batch_size: 32
eval_batch_size: 32
learning_rate: 0.0003
epochs: 20

